### ISSUE TITLE
Why FrozenDictionary<TKey, TValue> implements IDictionary<TKey, TValue>

### ISSUE THREAD

**Issue by Hermholtz** [geeknoid/FrozenCollections#2]
I had no chance of asking this question there: https://github.com/dotnet/runtime/issues/67209 therefore asking here.
`IDictionary<TKey, TValue>` contains mutator methods such as `Add`, `Remove` and setter for `Item[]`, why are you decided to implement this interface for immutable `FrozenDictionary` if they do nothing but throw `NotSupportedException`? Why would be the interface relevant at all?

```
public abstract class FrozenDictionary<TKey, TValue> :
        IDictionary<TKey, TValue>, IReadOnlyDictionary<TKey, TValue>, IDictionary
```

Thanks in advance.

**Comment by geeknoid** [comment]
It's the same rationale why ImmutableDictionary also implements IDictionary<K,V>. Basically, there are situations where API accept an IDictionary and only perform non-mutating operations on the objects. They should take an IReadOnlyDictionary, but alas they don't.

The worst case is with ICollection. ICollection is a mutable interface and several places in the framework type test to see if an IEnumerable is an ICollection, and then take advantage of the ICollection methods to improve efficiency. The issue there is that ICollection does not implement IReadOnlyCollection, which it really should. But it can't due to compat issues.

**Comment by Hermholtz** [comment]
Thanks for clarification. So it means that many methods take `IDictionary<K,V>` when they're not modifying its entries and instead should take `IReadOnlyDictionary<K,V>` . It seems it's similar to forgetting `const` in C++. Well I was on the same page when designing my APIs in the past, I think it wasn't stressed enough in the docs of `IDictionary<K,V>` and its most popular implementations (including `ConcurrentDictionary<K,V>`). I don't remember anything saying something like 'if your method doesn't modify the contents of dictionary, take the parameter of type `IReadOnlyDictionary<K,V>`.

> ICollection does not implement IReadOnlyCollection

Yeah and IDictionary<K,V> doesn't implement IReadOnlyDictionary<K,V> as well... https://github.com/dotnet/runtime/issues/34122

It's only that Dictionary<K,V> implements IReadOnlyDictionary...

Thanks again, closing it.
